### ISSUE TITLE
During auto-play, the screen prioritizes the text over the illustration

### ISSUE THREAD

**Issue by masarapmabuhay** [usbong/Usbong-iOS#2]
Salut! I noticed that during auto-play, the screen prioritizes the text over the illustration by scrolling downward until the last sentence of the text is shown, thereby causing the illustration to not be fully shown. Merci beaucoup!

**Comment by chrisamanse** [comment]
Can you provide more details on this issue (screenshots would be helpful)? Thank you.

**Comment by masarapmabuhay** [comment]
Salut! It seems that I can no longer replicate the bug. In any case, I'll be sure to capture screenshots when I can encounter it again. Merci beaucoup!
